OBJECTS = libHwME.so 

SOURCES := $(wildcard *.cc)

LIBOBJECTS := $(SOURCES:.cc=.o)

include ../Config/Makefile.common

$(OBJECTS): $(LIBOBJECTS)
	@cd $(SRCDIR)/lib; rm -f $(LIBOBJECTS)
	$(CXX) $(CXXFLAGS) $(CXXDEBUGFLAG) $(CXXOPTFLAG) $(CXXDLFLAGS) $(LIBOBJECTS) -o $@
	@ln -f -s `pwd`/$@ $(SRCDIR)/lib

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


MEee2gZ2bb.o: MEee2gZ2bb.cc MEee2gZ2bb.h\
	 ../../Pythia7/MatrixElement/ME2to2QCD.h \
	 ../../Pythia7/MatrixElement/ME2to2Base.h \
	 ../../Pythia7/MatrixElement/MEBase.h \
	 ../../Pythia7/Handlers/HandlerBase.h \
	 ../../Pythia7/Interface/Interfaced.h \
	 ../../Pythia7/Config/Pythia7.h \
	 ../../Pythia7/Config/config.h \
	 ../../Pythia7/Pointer/Ptr.h \
	 ../../Pythia7/Pointer/RCPtr.fh \
	 ../../Pythia7/Pointer/PtrTraits.h \
	 ../../Pythia7/Pointer/RCPtr.h \
	 ../../Pythia7/Pointer/ReferenceCounted.h \
	 ../../Pythia7/Pointer/ReferenceCounted.icc \
	 ../../Pythia7/Pointer/RCPtr.icc \
	 ../../Pythia7/Utilities/Rebinder.fh \
	 ../../Pythia7/Utilities/Interval.fh \
	 ../../Pythia7/Utilities/ClassDescription.fh \
	 ../../Pythia7/Interface/InterfaceBase.fh \
	 ../../Pythia7/Persistency/PersistentOStream.fh \
	 ../../Pythia7/Persistency/PersistentIStream.fh \
	 ../../Pythia7/Config/Units.h \
	 ../../Pythia7/CLHEPWrap/Lorentz5Vector.fh \
	 ../../Pythia7/CLHEPWrap/LorentzVector.fh \
	 ../../Pythia7/CLHEPWrap/ThreeVector.fh \
	 ../../Pythia7/CLHEPWrap/Transverse.fh \
	 ../../Pythia7/CLHEPWrap/SystemOfUnits.h \
	 ../../Pythia7/CLHEPWrap/CLHEP.h \
	 ../../Pythia7/Config/Constants.h \
	 ../../Pythia7/Config/std.h \
	 ../../Pythia7/Config/Pointers.h \
	 ../../Pythia7/Config/Containers.h \
	 ../../Pythia7/Utilities/FixedSizeAllocator.h \
	 ../../Pythia7/Utilities/Debug.h \
	 ../../Pythia7/Utilities/Debug.icc \
	 ../../Pythia7/Utilities/FixedSizeAllocator.icc \
	 ../../Pythia7/Interface/InterfacedBase.h \
	 ../../Pythia7/Misc/Named.h \
	 ../../Pythia7/Misc/Named.icc \
	 ../../Pythia7/Utilities/ClassDescription.h \
	 ../../Pythia7/Utilities/ClassTraits.h \
	 ../../Pythia7/Utilities/DescriptionList.h \
	 ../../Pythia7/Utilities/DescriptionList.icc \
	 ../../Pythia7/Utilities/ClassDescription.icc \
	 ../../Pythia7/Utilities/ClassDescription.tcc \
	 ../../Pythia7/Utilities/HoldFlag.h \
	 ../../Pythia7/Utilities/HoldFlag.icc \
	 ../../Pythia7/Interface/InterfacedBase.xh \
	 ../../Pythia7/Interface/InterfaceBase.h \
	 ../../Pythia7/Interface/InterfaceBase.xh \
	 ../../Pythia7/Misc/Exception.h \
	 ../../Pythia7/Misc/Exception.fh \
	 ../../Pythia7/Utilities/sstream.h \
	 ../../Pythia7/Misc/Exception.icc \
	 ../../Pythia7/Interface/InterfaceBase.icc \
	 ../../Pythia7/Interface/InterfacedBase.icc \
	 ../../Pythia7/Interface/Interfaced.icc \
	 ../../Pythia7/Handlers/HandlerBase.icc \
	 ../../Pythia7/EventRecord/SubProcess.h \
	 ../../Pythia7/EventRecord/Particle.h \
	 ../../Pythia7/EventRecord/EventConfig.h \
	 ../../Pythia7/CLHEPWrap/Lorentz5Vector.h \
	 ../../Pythia7/CLHEPWrap/LorentzVector.h \
	 ../../Pythia7/CLHEPWrap/Transverse.h \
	 ../../Pythia7/CLHEPWrap/Transverse.icc \
	 ../../Pythia7/Utilities/Direction.h \
	 ../../Pythia7/Utilities/Direction.xh \
	 ../../Pythia7/Utilities/Direction.icc \
	 ../../Pythia7/Utilities/Math.h \
	 ../../Pythia7/Utilities/Math.icc \
	 ../../Pythia7/CLHEPWrap/Lorentz5Vector.icc \
	 ../../Pythia7/CLHEPWrap/LorentzRotation.h \
	 ../../Pythia7/CLHEPWrap/LorentzRotation.fh \
	 ../../Pythia7/EventRecord/ColourBase.h \
	 ../../Pythia7/EventRecord/EventInfoBase.h \
	 ../../Pythia7/EventRecord/EventInfoBase.icc \
	 ../../Pythia7/EventRecord/ColourLine.h \
	 ../../Pythia7/EventRecord/ColourSinglet.h \
	 ../../Pythia7/EventRecord/ColourSinglet.icc \
	 ../../Pythia7/EventRecord/ColourLine.icc \
	 ../../Pythia7/EventRecord/ColourBase.icc \
	 ../../Pythia7/EventRecord/SpinBase.h \
	 ../../Pythia7/EventRecord/SpinBase.icc \
	 ../../Pythia7/EventRecord/Particle.icc \
	 ../../Pythia7/PDT/ParticleData.h \
	 ../../Pythia7/PDT/PDT.h \
	 ../../Pythia7/PDT/PDT.icc \
	 ../../Pythia7/CLHEPWrap/PhysicalConstants.h \
	 ../../Pythia7/Utilities/Selector.h \
	 ../../Pythia7/Utilities/Selector.icc \
	 ../../Pythia7/Utilities/Selector.tcc \
	 ../../Pythia7/PDT/WidthGenerator.fh \
	 ../../Pythia7/PDT/MassGenerator.fh \
	 ../../Pythia7/PDT/DecayMode.fh \
	 ../../Pythia7/PDT/ParticleData.icc \
	 ../../Pythia7/EventRecord/Particle.tcc \
	 ../../Pythia7/EventRecord/SubProcess.icc \
	 ../../Pythia7/EventRecord/SubProcess.tcc \
	 ../../Pythia7/MatrixElement/DiagramBase.h \
	 ../../Pythia7/MatrixElement/ColourLines.h \
	 ../../Pythia7/MatrixElement/ColourLines.icc \
	 ../../Pythia7/MatrixElement/DiagramBase.fh \
	 ../../Pythia7/MatrixElement/DiagramBase.xh \
	 ../../Pythia7/MatrixElement/DiagramBase.icc \
	 ../../Pythia7/MatrixElement/Amplitude.h \
	 ../../Pythia7/Config/Complex.h \
	 ../../Pythia7/MatrixElement/Amplitude.icc \
	 ../../Pythia7/Handlers/LastXCombInfo.h \
	 ../../Pythia7/PDF/PDF.fh \
	 ../../Pythia7/Handlers/LastXCombInfo.icc \
	 ../../Pythia7/MatrixElement/MEBase.icc \
	 ../../Pythia7/MatrixElement/Tree2toNDiagram.h \
	 ../../Pythia7/MatrixElement/Tree2toNDiagram.xh \
	 ../../Pythia7/MatrixElement/Tree2toNDiagram.icc \
	 ../../Pythia7/Interface/Switch.fh \
	 ../../Pythia7/MatrixElement/ME2to2Base.icc \
	 ../../Pythia7/MatrixElement/ME2to2QCD.icc \
	 ../../Pythia7/Interface/ClassDocumentation.h \
	 ../../Pythia7/Interface/ClassDocumentation.fh \
	 ../../Pythia7/Interface/ClassDocumentation.icc \
	 ../../Pythia7/PDT/EnumParticles.h \
	 ../../Pythia7/Utilities/Timer.h \
	 ../../Pythia7/Utilities/Timer.icc \
	 ../../Pythia7/Repository/EventGenerator.h \
	 ../../Pythia7/Repository/EventGenerator.fh \
	 ../../Pythia7/Repository/RandomGenerator.h \
	 ../../Pythia7/CLHEPWrap/RandomEngine.fh \
	 ../../Pythia7/Repository/RandomGenerator.icc \
	 ../../Pythia7/Repository/UseRandom.h \
	 ../../Pythia7/Repository/UseRandom.icc \
	 ../../Pythia7/Repository/CurrentGenerator.fh \
	 ../../Pythia7/Repository/EventGenerator.xh \
	 ../../Pythia7/Repository/EventGenerator.icc \
	 ../../Pythia7/Repository/EventGenerator.tcc \
	 ../../Pythia7/StandardModel/StandardModelBase.h \
	 ../../Pythia7/StandardModel/AlphaEMBase.h \
	 ../../Pythia7/StandardModel/StandardModelBase.fh \
	 ../../Pythia7/StandardModel/AlphaEMBase.icc \
	 ../../Pythia7/StandardModel/CKMBase.h \
	 ../../Pythia7/StandardModel/CKMBase.icc \
	 ../../Pythia7/StandardModel/AlphaSBase.h \
	 ../../Pythia7/StandardModel/AlphaSBase.icc \
	 ../../Pythia7/StandardModel/StandardModelBase.icc \
	 ../../Pythia7/Handlers/XComb.h \
	 ../../Pythia7/Handlers/SubProcessHandler.fh \
	 ../../Pythia7/PDF/PartonExtractor.fh \
	 ../../Pythia7/PDF/PartonBin.h \
	 ../../Pythia7/PDF/PDFBase.h \
	 ../../Pythia7/PDF/PDFCuts.h \
	 ../../Pythia7/Utilities/Interval.h \
	 ../../Pythia7/Utilities/Interval.icc \
	 ../../Pythia7/Utilities/Interval.tcc \
	 ../../Pythia7/PDF/PDFCuts.icc \
	 ../../Pythia7/PDF/PDFBase.xh \
	 ../../Pythia7/PDF/PDFBase.icc \
	 ../../Pythia7/PDF/PartonBin.icc \
	 ../../Pythia7/Utilities/VSelector.h \
	 ../../Pythia7/Utilities/VSelector.icc \
	 ../../Pythia7/Utilities/VSelector.tcc \
	 ../../Pythia7/Handlers/XComb.icc \
	 ../../Pythia7/Persistency/PersistentOStream.h \
	 ../../Pythia7/Persistency/PersistentOStream.xh \
	 ../../Pythia7/Persistency/PersistentOStream.icc \
	 ../../Pythia7/Persistency/PersistentIStream.h \
	 ../../Pythia7/Persistency/InputDescription.h \
	 ../../Pythia7/Persistency/InputDescription.icc \
	 ../../Pythia7/Persistency/PersistentIStream.icc \
	 ../../Pythia7/Persistency/PersistentIStream.tcc

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
