// -*- C++ -*-
//
// This is the implementation of the non-inlined, non-templated member
// functions of the MEPPto3D3Jet class.
//

#include "MEPPto3D3Jet.h"
#include "ThePEG/Interface/ClassDocumentation.h"
#include "ThePEG/Interface/Reference.h"
#include "ThePEG/Interface/Parameter.h"
#include "ThePEG/Interface/Switch.h"
#include "ThePEG/EventRecord/Particle.h"
#include "ThePEG/Repository/UseRandom.h"
#include "ThePEG/Repository/EventGenerator.h"
#include "ThePEG/Utilities/DescribeClass.h"
#include "ThePEG/Persistency/PersistentOStream.h"
#include "ThePEG/Persistency/PersistentIStream.h"
#include "ThePEG/PDT/EnumParticles.h"
#include "ThePEG/MatrixElement/Tree2toNDiagram.h"
#include "ThePEG/Utilities/EnumIO.h"
#include "ThePEG/StandardModel/StandardModelBase.h"
#include "ThePEG/Helicity/WaveFunction/Rank3TensorWaveFunction.h"
#include "ThePEG/Helicity/WaveFunction/VectorWaveFunction.h"
#include "Herwig/MatrixElement/ProductionMatrixElement.h"
#include "Herwig/MatrixElement/HardVertex.h"

using namespace Herwig;

void MEPPto3D3Jet::doinit() {
  HwMEBase::doinit();
  // get the non-perturbative ME
  O1_ = params_->singletMEProduction<2>(state_,n_,1,3);
  // set the mass option
  massOption(vector<unsigned int>({mOpt_+1,0}));
}

IBPtr MEPPto3D3Jet::clone() const {
  return new_ptr(*this);
}

IBPtr MEPPto3D3Jet::fullclone() const {
  return new_ptr(*this);
}

void MEPPto3D3Jet::persistentOutput(PersistentOStream & os) const {
  os << params_ << ounit(O1_,GeV*GeV2*GeV2*GeV2) << oenum(state_) << n_ << mOpt_;
}

void MEPPto3D3Jet::persistentInput(PersistentIStream & is, int) {
  is >> params_ >> iunit(O1_,GeV*GeV2*GeV2*GeV2) >> ienum(state_) >> n_ >> mOpt_;
}

//The following static variable is needed for the type
// description system in ThePEG.
DescribeClass<MEPPto3D3Jet,HwMEBase>
describeHerwigMEPPto3D3Jet("Herwig::MEPPto3D3Jet",
			   "HwOniumParameters.so HwMEHadronOnium.so");

void MEPPto3D3Jet::Init() {

  static ClassDocumentation<MEPPto3D3Jet> documentation
    ("The MEPPto3D3Jet class implements the g g to 3D3 g processes");

  static Reference<MEPPto3D3Jet,OniumParameters> interfaceParameters
    ("Parameters",
     "Quarkonium parameters",
     &MEPPto3D3Jet::params_, false, false, true, false, false);
  
  static Switch<MEPPto3D3Jet,OniumState> interfaceState
    ("State",
     "The type of onium state",
     &MEPPto3D3Jet::state_, ccbar, false, false);
  static SwitchOption interfaceStateccbar
    (interfaceState,
     "ccbar",
     "Charmonium state",
     ccbar);
  static SwitchOption interfaceStatebbbar
    (interfaceState,
     "bbbar",
     "Bottomonium state",
     bbbar);
  
  static Parameter<MEPPto3D3Jet,unsigned int> interfacePrincipalQuantumNumber
    ("PrincipalQuantumNumber",
     "The principle quantum number of the states",
     &MEPPto3D3Jet::n_, 1, 1, 10,
     false, false, Interface::limited);

  static Switch<MEPPto3D3Jet,unsigned int> interfaceMassOption
    ("MassOption",
     "Mass of the treatment of the 3D3 mass",
     &MEPPto3D3Jet::mOpt_, 0, false, false);
  static SwitchOption interfaceMassOptionOnShell
    (interfaceMassOption,
     "OnShell",
     "Use the on-shell mass",
     0);
  static SwitchOption interfaceMassOptionOffShell
    (interfaceMassOption,
     "OffShell",
     "Use an off-shell mass generated by the MassGenerator object for the 3D3 state.",
     1);
}

void MEPPto3D3Jet::getDiagrams() const {
  // construct the meson PDG code from quark ids
  unsigned int iq = 4+state_;
  tcPDPtr ps = getParticleData(long(iq*110 + 7 + (n_-1)*100000));
  tcPDPtr g = getParticleData(ParticleID::g);
  add(new_ptr((Tree2toNDiagram(2), g, g, 1, ps, 1, g , -1)));
}

Selector<MEBase::DiagramIndex>
MEPPto3D3Jet::diagrams(const DiagramVector & diags) const {
  Selector<DiagramIndex> sel;
  for ( DiagramIndex i = 0; i < diags.size(); ++i ) 
    if ( diags[i]->id() == -1 ) sel.insert(1.0, i);
  return sel;
}

Selector<const ColourLines *>
MEPPto3D3Jet::colourGeometries(tcDiagPtr ) const {
  static ColourLines c1("1 -2,  2  4, -1 -4");
  static ColourLines c2("1  4, -4 -2,  2 -1");
  Selector<const ColourLines *> sel;
  sel.insert(0.5, &c1);
  sel.insert(0.5, &c2);
  return sel;
}

Energy2 MEPPto3D3Jet::scale() const {
  return sHat();
}

double MEPPto3D3Jet::me2() const {
  Energy M = meMomenta()[2].mass();
  Energy2 M2=sqr(M);
  Energy4 um(sqr(uHat()-M2)),tm(sqr(tHat()-M2)),sm(sqr(sHat()-M2));
  double output = 80.*O1_*pow(Constants::pi*standardModel()->alphaS(scale()),3)/(189*pow<7,1>(M))*256.*sqr(M2)*
    (5*pow<3,1>(tHat())*pow<3,1>(uHat())*pow<3,1>(tHat()+uHat())*sqr(sqr(tHat())+tHat()*uHat()+sqr(uHat()))
     +2*pow<10,1>(M2)*(4*pow<3,1>(tHat())+9*sqr(tHat())*uHat()+9*tHat()*sqr(uHat())+4*pow<3,1>(uHat()))
     -2*pow<9,1>(M2)*(12*pow<4,1>(tHat())+64*pow<3,1>(tHat())*uHat()+103*sqr(tHat())*sqr(uHat())+64*tHat()*pow<3,1>(uHat())+12*pow<4,1>(uHat()))
     +pow<8,1>(M2)*(25*pow<5,1>(tHat())+300*pow<4,1>(tHat())*uHat()+826*pow<3,1>(tHat())*sqr(uHat())+826*sqr(tHat())*pow<3,1>(uHat())+300*tHat()*pow<4,1>(uHat())+25*pow<5,1>(uHat()))
     -5*M2*sqr(tHat())*sqr(uHat())*sqr(tHat()+uHat())*(pow<6,1>(tHat())+8*pow<5,1>(tHat())*uHat()+14*pow<4,1>(tHat())*sqr(uHat())
						       +16*pow<3,1>(tHat())*pow<3,1>(uHat())+14*sqr(tHat())*pow<4,1>(uHat())+8*tHat()*pow<5,1>(uHat())+pow<6,1>(uHat()))
     -pow<7,1>(M2)*(13*pow<6,1>(tHat())+356*pow<5,1>(tHat())*uHat()+1556*pow<4,1>(tHat())*sqr(uHat())+2424*pow<3,1>(tHat())*pow<3,1>(uHat())
		    +1556*sqr(tHat())*pow<4,1>(uHat())+356*tHat()*pow<5,1>(uHat())+13*pow<6,1>(uHat()))
     +pow<6,1>(M2)*(10*pow<7,1>(tHat())+283*pow<6,1>(tHat())*uHat()+1680*pow<5,1>(tHat())*sqr(uHat())+3717*pow<4,1>(tHat())*pow<3,1>(uHat())
		    +3717*pow<3,1>(tHat())*pow<4,1>(uHat())+1680*sqr(tHat())*pow<5,1>(uHat())+283*tHat()*pow<6,1>(uHat())+10*pow<7,1>(uHat()))
     -pow<5,1>(M2)*(10*pow<8,1>(tHat())+180*pow<7,1>(tHat())*uHat()+1201*pow<6,1>(tHat())*sqr(uHat())+3342*pow<5,1>(tHat())*pow<3,1>(uHat())+4624*pow<4,1>(tHat())*pow<4,1>(uHat())
		    +3342*pow<3,1>(tHat())*pow<5,1>(uHat())+1201*sqr(tHat())*pow<6,1>(uHat())+180*tHat()*pow<7,1>(uHat())+10*pow<8,1>(uHat()))
     +sqr(M2)*tHat()*uHat()*(3*pow<9,1>(tHat())+40*pow<8,1>(tHat())*uHat()+221*pow<7,1>(tHat())*sqr(uHat())+514*pow<6,1>(tHat())*pow<3,1>(uHat())
			     +698*pow<5,1>(tHat())*pow<4,1>(uHat())+698*pow<4,1>(tHat())*pow<5,1>(uHat())+514*pow<3,1>(tHat())*pow<6,1>(uHat())
			     +221*sqr(tHat())*pow<7,1>(uHat())+40*tHat()*pow<8,1>(uHat())+3*pow<9,1>(uHat()))
     +pow<4,1>(M2)*(5*pow<9,1>(tHat())+80*pow<8,1>(tHat())*uHat()+602*pow<7,1>(tHat())*sqr(uHat())+1943*pow<6,1>(tHat())*pow<3,1>(uHat())
		    +3307*pow<5,1>(tHat())*pow<4,1>(uHat())+3307*pow<4,1>(tHat())*pow<5,1>(uHat())+1943*pow<3,1>(tHat())*pow<6,1>(uHat())
		    +602*sqr(tHat())*pow<7,1>(uHat())+80*tHat()*pow<8,1>(uHat())+5*pow<9,1>(uHat()))
     -pow<3,1>(M2)*(pow<10,1>(tHat())+20*pow<9,1>(tHat())*uHat()+198*pow<8,1>(tHat())*sqr(uHat())+776*pow<7,1>(tHat())*pow<3,1>(uHat())
		    +1502*pow<6,1>(tHat())*pow<4,1>(uHat())+1812*pow<5,1>(tHat())*pow<5,1>(uHat())+1502*pow<4,1>(tHat())*pow<6,1>(uHat())
		    +776*pow<3,1>(tHat())*pow<7,1>(uHat())+198*sqr(tHat())*pow<8,1>(uHat())+20*tHat()*pow<9,1>(uHat())+pow<10,1>(uHat())))
    /(15.*pow<5,1>(M2-tHat())*pow<5,1>(M2-uHat())*pow<5,1>(tHat()+uHat()));
  // test vs PRD 45, 116
  // Energy7 R02 = params_->secondDerivativeRadialWaveFunctionSquared(state_,n_);
  // Energy6 Q(sHat()*tHat()*uHat());
  // Energy4 P(sHat()*tHat()+tHat()*uHat()+uHat()*sHat());
  // double test = 5120.*sqr(Constants::pi)*pow(standardModel()->alphaS(scale()),3)*R02
  //   /(9.*pow<3,1>(M)*pow<5,1>(Q-M2*P))*
  //   (-pow<3,1>(M2)*pow<5,1>(P) + 3*sqr(M2)*pow<4,1>(P)*Q - 
  //    8*pow<7,1>(M2)*sqr(Q) + 111*pow<4,1>(M2)*pow<3,1>(Q) - 20*M2*pow<4,1>(Q) + 
  //    sqr(M2)*P*Q*(6*pow<6,1>(M2) - 173*pow<3,1>(M2)*Q - 14*sqr(Q)) - M2*pow<3,1>(P)*
  //    (8*pow<6,1>(M2) + 25*pow<3,1>(M2)*Q + 5*sqr(Q)) + 
  //    sqr(P)*Q*(68*pow<6,1>(M2) + 61*pow<3,1>(M2)*Q + 5*sqr(Q)));
  // cerr << "testing matrix element " << output << " " << test << " "
  //      << (output-test)/(output+test) << " " << output/test << "\n";
  return output;
}

void MEPPto3D3Jet::constructVertex(tSubProPtr sub) {
  using namespace ThePEG::Helicity;
  // extract the particles in the hard process
  // only one order
  ParticleVector hard;
  hard.reserve(4);
  hard.push_back(sub->incoming().first);
  hard.push_back(sub->incoming().second);
  hard.push_back(sub->outgoing()[0]);
  hard.push_back(sub->outgoing()[1]);
  // boost to partonic CMS
  Lorentz5Momentum pcms = hard[0]->momentum()+hard[1]->momentum();
  LorentzRotation boost(-pcms.boostVector());
  for(PPtr part : hard) part->transform(boost);
  // set the wavefunctions
  vector<VectorWaveFunction> g1,g2,g4;
  vector<Rank3TensorWaveFunction> psi;
  VectorWaveFunction( g1,hard[0],incoming,false, true,true,vector_phase);
  VectorWaveFunction( g2,hard[1],incoming,false, true,true,vector_phase);
  Rank3TensorWaveFunction(psi,hard[2],outgoing,true ,false,true);
  VectorWaveFunction( g4,hard[3],outgoing,true , true,true,vector_phase);
  // extract kinematic variables
  Energy M = hard[2]->mass();
  Energy2 M2 = sqr(hard[2]->mass());
  double phi = hard[2]->momentum().phi();
  Energy2 sh = (hard[0]->momentum()+hard[1]->momentum()).m2();
  Energy2 th = (hard[0]->momentum()-hard[2]->momentum()).m2();
  Energy2 uh = (hard[0]->momentum()-hard[3]->momentum()).m2();
  Energy2 um(uh-M2),tm(th-M2),sm(sh-M2);
  Complex phase = exp(Complex(0.,phi));
  // Energy rstu = sqrt(th*uh/sh);
  // calculate the matrix element
  ProductionMatrixElement me(PDT::Spin1,PDT::Spin1,PDT::Spin3,PDT::Spin1);
  me(0,0,0,0)=(8*sqr(M2)*pow(phase,4)*th*uh*(pow<3,1>(M2)*(sh+uh)-sqr(M2)*uh*(2*sh+uh)-M2*sh*(sqr(sh)+2*sh*uh-sqr(uh))+sqr(sh)*(sqr(sh)+3*sh*uh+3*sqr(uh))))/(sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,0,0,2)=0;
  me(0,0,1,0)=(8*sqrt(0.6666666666666666)*pow<3,1>(M)*pow(phase,3)*sqrt(sh)*(th-uh)*sqrt(th*uh)*(-(pow<3,1>(M2)*(sh+uh))-sqr(sh)*uh*(sh+uh)+sqr(M2)*(sqr(sh)+4*sh*uh+sqr(uh))-M2*sh*(sqr(sh)+2*sh*uh+3*sqr(uh))))/(sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,0,1,2)=0;
  me(0,0,2,0)=(8*M2*sqr(phase)*sh*(2*sqr(th)*sqr(uh)*sqr(th+uh)+2*pow<4,1>(M2)*(sqr(th)-th*uh+sqr(uh))+pow<3,1>(M2)*(-3*pow<3,1>(th)+sqr(th)*uh+th*sqr(uh)-3*pow<3,1>(uh))+M2*th*uh*(3*pow<3,1>(th)-11*sqr(th)*uh-11*th*sqr(uh)+3*pow<3,1>(uh))+sqr(M2)*(pow<4,1>(th)-2*pow<3,1>(th)*uh+12*sqr(th)*sqr(uh)-2*th*pow<3,1>(uh)+pow<4,1>(uh))))/(sqrt(15)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,0,2,2)=0;
  me(0,0,3,0)=(8*pow<3,1>(M)*phase*sh*sqrt(sh)*(th-uh)*sqrt(th*uh)*(pow<3,1>(M2)-3*M2*th*uh-sqr(M2)*(th+uh)+2*th*uh*(th+uh)))/(sqrt(5)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,0,3,2)=0;
  me(0,0,4,0)=(8*M2*sqr(sh)*th*uh*(pow<3,1>(M2)-3*M2*th*uh+th*uh*(th+uh)))/(sqrt(15)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,0,4,2)=0;
  me(0,0,5,0)=0;
  me(0,0,5,2)=0;
  me(0,0,6,0)=0;
  me(0,0,6,2)=0;
  me(0,2,0,0)=(8*sqr(M2)*sqr(phase)*sh*sqr(uh)*(pow<4,1>(M2)*(th+uh)+3*sqr(M2)*th*uh*(th+uh)+pow<3,1>(th)*uh*(th+uh)-pow<3,1>(M2)*uh*(4*th+uh)-M2*sqr(th)*uh*(3*th+2*uh)))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,0,2)=(8*sqr(M2)*sqr(sh)*th*pow<3,1>(uh)*(3*sqr(M2)+sqr(th)+th*uh+sqr(uh)-3*M2*(th+uh)))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,1,0)=(-8*sqrt(0.6666666666666666)*pow<3,1>(M)*phase*sqrt(sh)*(pow<5,1>(M2)*(sh+th)+sqr(sh)*pow<3,1>(th)*(sh+th)-pow<4,1>(M2)*th*(5*sh+3*th)-M2*sh*sqr(th)*(2*sqr(sh)+sh*th-2*sqr(th))+sqr(M2)*sh*th*(5*sqr(sh)+7*sh*th-2*sqr(th))-pow<3,1>(M2)*(pow<3,1>(sh)+sqr(sh)*th-7*sh*sqr(th)-2*pow<3,1>(th)))*uh*sqrt(th*uh))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,1,2)=(8*sqrt(0.6666666666666666)*pow<3,1>(M)*sh*sqrt(sh)*sqr(uh)*sqrt(th*uh)*(th*sqr(uh)*(th+uh)+pow<3,1>(M2)*(-7*th+2*uh)+sqr(M2)*(9*sqr(th)+6*th*uh-3*sqr(uh))+M2*(-3*pow<3,1>(th)-4*sqr(th)*uh-3*th*sqr(uh)+pow<3,1>(uh))))/(phase*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,2,0)=(8*M2*th*(pow<6,1>(M2)*(sh+th)+pow<3,1>(sh)*pow<3,1>(th)*(sh+th)+M2*sqr(sh)*pow<3,1>(th)*(9*sh+10*th)+pow<5,1>(M2)*(9*sqr(sh)+2*sh*th-sqr(th))-pow<4,1>(M2)*(15*pow<3,1>(sh)+48*sqr(sh)*th+14*sh*sqr(th)+pow<3,1>(th))+sqr(M2)*sh*th*(9*pow<3,1>(sh)-sqr(sh)*th-17*sh*sqr(th)+3*pow<3,1>(th))+pow<3,1>(M2)*(5*pow<4,1>(sh)+36*pow<3,1>(sh)*th+61*sqr(sh)*sqr(th)+8*sh*pow<3,1>(th)+pow<4,1>(th)))*uh)/(sqrt(15)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,2,2)=(8*M2*sh*(2*sqr(sh)*sqr(th)*sqr(sh+th)+pow<4,1>(M2)*(2*sqr(sh)-6*sh*th+7*sqr(th))+M2*sh*th*(3*pow<3,1>(sh)+11*sqr(sh)*th+15*sh*sqr(th)+7*pow<3,1>(th))-pow<3,1>(M2)*(3*pow<3,1>(sh)+5*sqr(sh)*th-16*sh*sqr(th)+12*pow<3,1>(th))+sqr(M2)*(pow<4,1>(sh)+8*pow<3,1>(sh)*th+9*sqr(sh)*sqr(th)-7*sh*pow<3,1>(th)+6*pow<4,1>(th)))*sqr(uh))/(sqrt(15)*sqr(phase)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,3,0)=(-8*pow<3,1>(M)*sqrt(sh)*th*(2*pow<4,1>(M2)*sh*(2*sh-3*th)+pow<5,1>(M2)*(3*sh+th)+2*sqr(sh)*sqr(th)*(sqr(sh)+3*sh*th+2*sqr(th))+M2*sh*sqr(th)*(-7*sqr(sh)-5*sh*th+4*sqr(th))-pow<3,1>(M2)*(15*pow<3,1>(sh)+31*sqr(sh)*th+3*sh*sqr(th)+3*pow<3,1>(th))+2*sqr(M2)*(4*pow<4,1>(sh)+18*pow<3,1>(sh)*th+19*sqr(sh)*sqr(th)+sh*pow<3,1>(th)+pow<4,1>(th)))*sqrt(th*uh))/(sqrt(5)*phase*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,3,2)=(-8*pow<3,1>(M)*sqrt(sh)*uh*sqrt(th*uh)*(2*pow<4,1>(M2)*sh*(2*sh-3*uh)+pow<5,1>(M2)*(3*sh+uh)+2*sqr(sh)*sqr(uh)*(sqr(sh)+3*sh*uh+2*sqr(uh))+M2*sh*sqr(uh)*(-7*sqr(sh)-5*sh*uh+4*sqr(uh))-pow<3,1>(M2)*(15*pow<3,1>(sh)+31*sqr(sh)*uh+3*sh*sqr(uh)+3*pow<3,1>(uh))+2*sqr(M2)*(4*pow<4,1>(sh)+18*pow<3,1>(sh)*uh+19*sqr(sh)*sqr(uh)+sh*pow<3,1>(uh)+pow<4,1>(uh))))/(sqrt(5)*pow(phase,3)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,4,0)=(8*M2*sh*sqr(th)*(2*sqr(sh)*sqr(uh)*sqr(sh+uh)+pow<4,1>(M2)*(2*sqr(sh)-6*sh*uh+7*sqr(uh))+M2*sh*uh*(3*pow<3,1>(sh)+11*sqr(sh)*uh+15*sh*sqr(uh)+7*pow<3,1>(uh))-pow<3,1>(M2)*(3*pow<3,1>(sh)+5*sqr(sh)*uh-16*sh*sqr(uh)+12*pow<3,1>(uh))+sqr(M2)*(pow<4,1>(sh)+8*pow<3,1>(sh)*uh+9*sqr(sh)*sqr(uh)-7*sh*pow<3,1>(uh)+6*pow<4,1>(uh))))/(sqrt(15)*sqr(phase)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,4,2)=(8*M2*th*uh*(pow<6,1>(M2)*(sh+uh)+pow<3,1>(sh)*pow<3,1>(uh)*(sh+uh)+M2*sqr(sh)*pow<3,1>(uh)*(9*sh+10*uh)+pow<5,1>(M2)*(9*sqr(sh)+2*sh*uh-sqr(uh))-pow<4,1>(M2)*(15*pow<3,1>(sh)+48*sqr(sh)*uh+14*sh*sqr(uh)+pow<3,1>(uh))+sqr(M2)*sh*uh*(9*pow<3,1>(sh)-sqr(sh)*uh-17*sh*sqr(uh)+3*pow<3,1>(uh))+pow<3,1>(M2)*(5*pow<4,1>(sh)+36*pow<3,1>(sh)*uh+61*sqr(sh)*sqr(uh)+8*sh*pow<3,1>(uh)+pow<4,1>(uh))))/(sqrt(15)*pow(phase,4)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,5,0)=(8*sqrt(0.6666666666666666)*pow<3,1>(M)*sh*sqrt(sh)*sqr(th)*sqrt(th*uh)*(pow<3,1>(M2)*(2*th-7*uh)+sqr(th)*uh*(th+uh)+sqr(M2)*(-3*sqr(th)+6*th*uh+9*sqr(uh))+M2*(pow<3,1>(th)-3*sqr(th)*uh-4*th*sqr(uh)-3*pow<3,1>(uh))))/(pow(phase,3)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,5,2)=(-8*sqrt(0.6666666666666666)*pow<3,1>(M)*sqrt(sh)*th*sqrt(th*uh)*(pow<5,1>(M2)*(sh+uh)+sqr(sh)*pow<3,1>(uh)*(sh+uh)-pow<4,1>(M2)*uh*(5*sh+3*uh)-M2*sh*sqr(uh)*(2*sqr(sh)+sh*uh-2*sqr(uh))+sqr(M2)*sh*uh*(5*sqr(sh)+7*sh*uh-2*sqr(uh))-pow<3,1>(M2)*(pow<3,1>(sh)+sqr(sh)*uh-7*sh*sqr(uh)-2*pow<3,1>(uh))))/(pow(phase,5)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,6,0)=(8*sqr(M2)*sqr(sh)*pow<3,1>(th)*uh*(3*sqr(M2)+sqr(th)+th*uh+sqr(uh)-3*M2*(th+uh)))/(pow(phase,4)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(0,2,6,2)=(8*sqr(M2)*sh*sqr(th)*(pow<4,1>(M2)*(th+uh)+3*sqr(M2)*th*uh*(th+uh)+th*pow<3,1>(uh)*(th+uh)-M2*th*sqr(uh)*(2*th+3*uh)-pow<3,1>(M2)*th*(th+4*uh)))/(pow(phase,6)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,0,0)=(8*sqr(M2)*pow(phase,6)*sh*sqr(th)*(pow<4,1>(M2)*(th+uh)+3*sqr(M2)*th*uh*(th+uh)+th*pow<3,1>(uh)*(th+uh)-M2*th*sqr(uh)*(2*th+3*uh)-pow<3,1>(M2)*th*(th+4*uh)))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,0,2)=(8*sqr(M2)*pow(phase,4)*sqr(sh)*pow<3,1>(th)*uh*(3*sqr(M2)+sqr(th)+th*uh+sqr(uh)-3*M2*(th+uh)))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,1,0)=(8*sqrt(0.6666666666666666)*pow<3,1>(M)*pow(phase,5)*sqrt(sh)*th*sqrt(th*uh)*(pow<5,1>(M2)*(sh+uh)+sqr(sh)*pow<3,1>(uh)*(sh+uh)-pow<4,1>(M2)*uh*(5*sh+3*uh)-M2*sh*sqr(uh)*(2*sqr(sh)+sh*uh-2*sqr(uh))+sqr(M2)*sh*uh*(5*sqr(sh)+7*sh*uh-2*sqr(uh))-pow<3,1>(M2)*(pow<3,1>(sh)+sqr(sh)*uh-7*sh*sqr(uh)-2*pow<3,1>(uh))))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,1,2)=(-8*sqrt(0.6666666666666666)*pow<3,1>(M)*pow(phase,3)*sh*sqrt(sh)*sqr(th)*sqrt(th*uh)*(pow<3,1>(M2)*(2*th-7*uh)+sqr(th)*uh*(th+uh)+sqr(M2)*(-3*sqr(th)+6*th*uh+9*sqr(uh))+M2*(pow<3,1>(th)-3*sqr(th)*uh-4*th*sqr(uh)-3*pow<3,1>(uh))))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,2,0)=(8*M2*pow(phase,4)*th*uh*(pow<6,1>(M2)*(sh+uh)+pow<3,1>(sh)*pow<3,1>(uh)*(sh+uh)+M2*sqr(sh)*pow<3,1>(uh)*(9*sh+10*uh)+pow<5,1>(M2)*(9*sqr(sh)+2*sh*uh-sqr(uh))-pow<4,1>(M2)*(15*pow<3,1>(sh)+48*sqr(sh)*uh+14*sh*sqr(uh)+pow<3,1>(uh))+sqr(M2)*sh*uh*(9*pow<3,1>(sh)-sqr(sh)*uh-17*sh*sqr(uh)+3*pow<3,1>(uh))+pow<3,1>(M2)*(5*pow<4,1>(sh)+36*pow<3,1>(sh)*uh+61*sqr(sh)*sqr(uh)+8*sh*pow<3,1>(uh)+pow<4,1>(uh))))/(sqrt(15)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,2,2)=(8*M2*sqr(phase)*sh*sqr(th)*(2*sqr(sh)*sqr(uh)*sqr(sh+uh)+pow<4,1>(M2)*(2*sqr(sh)-6*sh*uh+7*sqr(uh))+M2*sh*uh*(3*pow<3,1>(sh)+11*sqr(sh)*uh+15*sh*sqr(uh)+7*pow<3,1>(uh))-pow<3,1>(M2)*(3*pow<3,1>(sh)+5*sqr(sh)*uh-16*sh*sqr(uh)+12*pow<3,1>(uh))+sqr(M2)*(pow<4,1>(sh)+8*pow<3,1>(sh)*uh+9*sqr(sh)*sqr(uh)-7*sh*pow<3,1>(uh)+6*pow<4,1>(uh))))/(sqrt(15)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,3,0)=(8*pow<3,1>(M)*pow(phase,3)*sqrt(sh)*uh*sqrt(th*uh)*(2*pow<4,1>(M2)*sh*(2*sh-3*uh)+pow<5,1>(M2)*(3*sh+uh)+2*sqr(sh)*sqr(uh)*(sqr(sh)+3*sh*uh+2*sqr(uh))+M2*sh*sqr(uh)*(-7*sqr(sh)-5*sh*uh+4*sqr(uh))-pow<3,1>(M2)*(15*pow<3,1>(sh)+31*sqr(sh)*uh+3*sh*sqr(uh)+3*pow<3,1>(uh))+2*sqr(M2)*(4*pow<4,1>(sh)+18*pow<3,1>(sh)*uh+19*sqr(sh)*sqr(uh)+sh*pow<3,1>(uh)+pow<4,1>(uh))))/(sqrt(5)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,3,2)=(8*pow<3,1>(M)*phase*sqrt(sh)*th*(2*pow<4,1>(M2)*sh*(2*sh-3*th)+pow<5,1>(M2)*(3*sh+th)+2*sqr(sh)*sqr(th)*(sqr(sh)+3*sh*th+2*sqr(th))+M2*sh*sqr(th)*(-7*sqr(sh)-5*sh*th+4*sqr(th))-pow<3,1>(M2)*(15*pow<3,1>(sh)+31*sqr(sh)*th+3*sh*sqr(th)+3*pow<3,1>(th))+2*sqr(M2)*(4*pow<4,1>(sh)+18*pow<3,1>(sh)*th+19*sqr(sh)*sqr(th)+sh*pow<3,1>(th)+pow<4,1>(th)))*sqrt(th*uh))/(sqrt(5)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,4,0)=(8*M2*sqr(phase)*sh*(2*sqr(sh)*sqr(th)*sqr(sh+th)+pow<4,1>(M2)*(2*sqr(sh)-6*sh*th+7*sqr(th))+M2*sh*th*(3*pow<3,1>(sh)+11*sqr(sh)*th+15*sh*sqr(th)+7*pow<3,1>(th))-pow<3,1>(M2)*(3*pow<3,1>(sh)+5*sqr(sh)*th-16*sh*sqr(th)+12*pow<3,1>(th))+sqr(M2)*(pow<4,1>(sh)+8*pow<3,1>(sh)*th+9*sqr(sh)*sqr(th)-7*sh*pow<3,1>(th)+6*pow<4,1>(th)))*sqr(uh))/(sqrt(15)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,4,2)=(8*M2*th*(pow<6,1>(M2)*(sh+th)+pow<3,1>(sh)*pow<3,1>(th)*(sh+th)+M2*sqr(sh)*pow<3,1>(th)*(9*sh+10*th)+pow<5,1>(M2)*(9*sqr(sh)+2*sh*th-sqr(th))-pow<4,1>(M2)*(15*pow<3,1>(sh)+48*sqr(sh)*th+14*sh*sqr(th)+pow<3,1>(th))+sqr(M2)*sh*th*(9*pow<3,1>(sh)-sqr(sh)*th-17*sh*sqr(th)+3*pow<3,1>(th))+pow<3,1>(M2)*(5*pow<4,1>(sh)+36*pow<3,1>(sh)*th+61*sqr(sh)*sqr(th)+8*sh*pow<3,1>(th)+pow<4,1>(th)))*uh)/(sqrt(15)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,5,0)=(-8*sqrt(0.6666666666666666)*pow<3,1>(M)*phase*sh*sqrt(sh)*sqr(uh)*sqrt(th*uh)*(th*sqr(uh)*(th+uh)+pow<3,1>(M2)*(-7*th+2*uh)+sqr(M2)*(9*sqr(th)+6*th*uh-3*sqr(uh))+M2*(-3*pow<3,1>(th)-4*sqr(th)*uh-3*th*sqr(uh)+pow<3,1>(uh))))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,5,2)=(8*sqrt(0.6666666666666666)*pow<3,1>(M)*sqrt(sh)*(pow<5,1>(M2)*(sh+th)+sqr(sh)*pow<3,1>(th)*(sh+th)-pow<4,1>(M2)*th*(5*sh+3*th)-M2*sh*sqr(th)*(2*sqr(sh)+sh*th-2*sqr(th))+sqr(M2)*sh*th*(5*sqr(sh)+7*sh*th-2*sqr(th))-pow<3,1>(M2)*(pow<3,1>(sh)+sqr(sh)*th-7*sh*sqr(th)-2*pow<3,1>(th)))*uh*sqrt(th*uh))/(phase*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,6,0)=(8*sqr(M2)*sqr(sh)*th*pow<3,1>(uh)*(3*sqr(M2)+sqr(th)+th*uh+sqr(uh)-3*M2*(th+uh)))/(pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,0,6,2)=(8*sqr(M2)*sh*sqr(uh)*(pow<4,1>(M2)*(th+uh)+3*sqr(M2)*th*uh*(th+uh)+pow<3,1>(th)*uh*(th+uh)-pow<3,1>(M2)*uh*(4*th+uh)-M2*sqr(th)*uh*(3*th+2*uh)))/(sqr(phase)*pow<4,1>(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,2,0,0)=0;
  me(2,2,0,2)=0;
  me(2,2,1,0)=0;
  me(2,2,1,2)=0;
  me(2,2,2,0)=0;
  me(2,2,2,2)=(8*M2*sqr(sh)*th*uh*(pow<3,1>(M2)-3*M2*th*uh+th*uh*(th+uh)))/(sqrt(15)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,2,3,0)=0;
  me(2,2,3,2)=(-8*pow<3,1>(M)*sh*sqrt(sh)*(th-uh)*sqrt(th*uh)*(pow<3,1>(M2)-3*M2*th*uh-sqr(M2)*(th+uh)+2*th*uh*(th+uh)))/(sqrt(5)*phase*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,2,4,0)=0;
  me(2,2,4,2)=(8*M2*sh*(2*sqr(th)*sqr(uh)*sqr(th+uh)+2*pow<4,1>(M2)*(sqr(th)-th*uh+sqr(uh))+pow<3,1>(M2)*(-3*pow<3,1>(th)+sqr(th)*uh+th*sqr(uh)-3*pow<3,1>(uh))+M2*th*uh*(3*pow<3,1>(th)-11*sqr(th)*uh-11*th*sqr(uh)+3*pow<3,1>(uh))+sqr(M2)*(pow<4,1>(th)-2*pow<3,1>(th)*uh+12*sqr(th)*sqr(uh)-2*th*pow<3,1>(uh)+pow<4,1>(uh))))/(sqrt(15)*sqr(phase)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,2,5,0)=0;
  me(2,2,5,2)=(-8*sqrt(0.6666666666666666)*pow<3,1>(M)*sqrt(sh)*(th-uh)*sqrt(th*uh)*(-(pow<3,1>(M2)*(sh+uh))-sqr(sh)*uh*(sh+uh)+sqr(M2)*(sqr(sh)+4*sh*uh+sqr(uh))-M2*sh*(sqr(sh)+2*sh*uh+3*sqr(uh))))/(pow(phase,3)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  me(2,2,6,0)=0;
  me(2,2,6,2)=(8*sqr(M2)*th*uh*(pow<3,1>(M2)*(sh+uh)-sqr(M2)*uh*(2*sh+uh)-M2*sh*(sqr(sh)+2*sh*uh-sqr(uh))+sqr(sh)*(sqr(sh)+3*sh*uh+3*sqr(uh))))/(pow(phase,4)*sqr(sm)*pow<3,1>(tm)*pow<3,1>(um));
  //  test the spin averaged result
  // Energy6 Q(sh*th*uh);
  // Energy4 P(sh*th+th*uh+uh*sh);
  // double test = 256.*sqr(M2)/15./pow<5,1>(Q-M2*P)*
  //   (-pow<3,1>(M2)*pow<5,1>(P) + 3*sqr(M2)*pow<4,1>(P)*Q - 
  //    8*pow<7,1>(M2)*sqr(Q) + 111*pow<4,1>(M2)*pow<3,1>(Q) - 20*M2*pow<4,1>(Q) + 
  //    sqr(M2)*P*Q*(6*pow<6,1>(M2) - 173*pow<3,1>(M2)*Q - 14*sqr(Q)) - M2*pow<3,1>(P)*
  //    (8*pow<6,1>(M2) + 25*pow<3,1>(M2)*Q + 5*sqr(Q)) + 
  //    sqr(P)*Q*(68*pow<6,1>(M2) + 61*pow<3,1>(M2)*Q + 5*sqr(Q)));
  // double aver = me.average();
  // cerr << "testing spin correlations " << test << " " << me.average() << " "
  //      << abs(test-aver)/(test+aver) << "\n";
  // construct the vertex
  HardVertexPtr hardvertex = new_ptr(HardVertex());
  // // set the matrix element for the vertex
  hardvertex->ME(me);
  // set the pointers and to and from the vertex
  for(unsigned int i = 0; i < hard.size(); ++i)
    hard[i]->spinInfo()->productionVertex(hardvertex);
  // boost back to lab
  boost = LorentzRotation(pcms.boostVector());
  for(PPtr part : hard)
    part->transform(boost);
}
