// -*- C++ -*-
//
// This is the implementation of the non-inlined, non-templated member
// functions of the MEPPto3S1Jet class.
//

#include "MEPPto3S1Jet.h"
#include "ThePEG/Interface/ClassDocumentation.h"
#include "ThePEG/Interface/Reference.h"
#include "ThePEG/Interface/Parameter.h"
#include "ThePEG/Interface/Switch.h"
#include "ThePEG/EventRecord/Particle.h"
#include "ThePEG/Repository/UseRandom.h"
#include "ThePEG/Repository/EventGenerator.h"
#include "ThePEG/Utilities/DescribeClass.h"
#include "ThePEG/Persistency/PersistentOStream.h"
#include "ThePEG/Persistency/PersistentIStream.h"
#include "ThePEG/PDT/EnumParticles.h"
#include "ThePEG/MatrixElement/Tree2toNDiagram.h"
#include "ThePEG/Utilities/EnumIO.h"
#include "ThePEG/StandardModel/StandardModelBase.h"
#include "ThePEG/Helicity/WaveFunction/VectorWaveFunction.h"
#include "Herwig/MatrixElement/ProductionMatrixElement.h"
#include "Herwig/MatrixElement/HardVertex.h"

using namespace Herwig;

void MEPPto3S1Jet::doinit() {
  HwMEBase::doinit();
  // get the non-perturbative ME
  O1_ = params_->singletMEProduction<0>(state_,n_,1,1);
  // set the mass option
  massOption(vector<unsigned int>({mOpt_+1,0}));
}

IBPtr MEPPto3S1Jet::clone() const {
  return new_ptr(*this);
}

IBPtr MEPPto3S1Jet::fullclone() const {
  return new_ptr(*this);
}

void MEPPto3S1Jet::persistentOutput(PersistentOStream & os) const {
  os << params_ << ounit(O1_,GeV*GeV2) << oenum(state_) << n_ << mOpt_;
}

void MEPPto3S1Jet::persistentInput(PersistentIStream & is, int) {
  is >> params_ >> iunit(O1_,GeV*GeV2) >> ienum(state_) >> n_ >> mOpt_;
}

//The following static variable is needed for the type
// description system in ThePEG.
DescribeClass<MEPPto3S1Jet,HwMEBase>
describeHerwigMEPPto3S1Jet("Herwig::MEPPto3S1Jet",
			     "HwOniumParameters.so HwMEHadronOnium.so");

void MEPPto3S1Jet::Init() {

  static ClassDocumentation<MEPPto3S1Jet> documentation
    ("The MEPPto3S1Jet class implements the g g to 3S1 g processes");

  static Reference<MEPPto3S1Jet,OniumParameters> interfaceParameters
    ("Parameters",
     "Quarkonium parameters",
     &MEPPto3S1Jet::params_, false, false, true, false, false);
  
  static Switch<MEPPto3S1Jet,OniumState> interfaceState
    ("State",
     "The type of onium state",
     &MEPPto3S1Jet::state_, ccbar, false, false);
  static SwitchOption interfaceStateccbar
    (interfaceState,
     "ccbar",
     "Charmonium state",
     ccbar);
  static SwitchOption interfaceStatebbbar
    (interfaceState,
     "bbbar",
     "Bottomonium state",
     bbbar);
  
  static Parameter<MEPPto3S1Jet,unsigned int> interfacePrincipalQuantumNumber
    ("PrincipalQuantumNumber",
     "The principle quantum number of the states",
     &MEPPto3S1Jet::n_, 1, 1, 10,
     false, false, Interface::limited);

  static Switch<MEPPto3S1Jet,unsigned int> interfaceMassOption
    ("MassOption",
     "Mass of the treatment of the 3S1 mass",
     &MEPPto3S1Jet::mOpt_, 0, false, false);
  static SwitchOption interfaceMassOptionOnShell
    (interfaceMassOption,
     "OnShell",
     "Use the on-shell mass",
     0);
  static SwitchOption interfaceMassOptionOffShell
    (interfaceMassOption,
     "OffShell",
     "Use an off-shell mass generated by the MassGenerator object for the 3S1 state.",
     1);
}

void MEPPto3S1Jet::getDiagrams() const {
  // construct the meson PDG code from quark ids
  unsigned int iq = 4+state_;
  tcPDPtr ps = getParticleData(long(iq*110+3 + (n_-1)*100000));
  tcPDPtr g = getParticleData(ParticleID::g);
  add(new_ptr((Tree2toNDiagram(2), g, g, 1, ps, 1, g , -1)));
}

Selector<MEBase::DiagramIndex>
MEPPto3S1Jet::diagrams(const DiagramVector & diags) const {
  Selector<DiagramIndex> sel;
  for ( DiagramIndex i = 0; i < diags.size(); ++i ) 
    if ( diags[i]->id() == -1 ) sel.insert(1.0, i);
  return sel;
}

Selector<const ColourLines *>
MEPPto3S1Jet::colourGeometries(tcDiagPtr ) const {
  static ColourLines c1("1 -2,  2  4, -1 -4");
  static ColourLines c2("1  4, -4 -2,  2 -1");
  Selector<const ColourLines *> sel;
  sel.insert(0.5, &c1);
  sel.insert(0.5, &c2);
  return sel;
}

Energy2 MEPPto3S1Jet::scale() const {
  return sHat();
}

double MEPPto3S1Jet::me2() const {
  Energy M = meMomenta()[2].mass();
  Energy2 M2=sqr(M);
  Energy4 um(sqr(uHat()-M2)),tm(sqr(tHat()-M2)),sm(sqr(sHat()-M2));
  double output = 160./81.*pow(Constants::pi*standardModel()->alphaS(scale()),3)*M*O1_*
    (sqr(sHat())*sm+sqr(tHat())*tm+sqr(uHat())*um)/(sm*tm*um);
  // test vs NPB 291 731
  // Energy3 R02 = params_->radialWaveFunctionSquared(state_,n_);
  // double test = 16.*Constants::pi*sqr(sHat())*
  //   5*Constants::pi*pow(standardModel()->alphaS(scale()),3)*R02*M/9./sqr(sHat())*
  //   (sqr(sHat()/(tHat()-M2)/(uHat()-M2))+sqr(tHat()/(sHat()-M2)/(uHat()-M2))+sqr(uHat()/(sHat()-M2)/(tHat()-M2)));
  // cerr << "testing matrix element " << output << " " << test << " "
  //      << (output-test)/(output+test) << " " << output/test << "\n";
  return output;
}


void MEPPto3S1Jet::constructVertex(tSubProPtr sub) {
  using namespace ThePEG::Helicity;
  // extract the particles in the hard process
  // only one order
  ParticleVector hard;
  hard.reserve(4);
  hard.push_back(sub->incoming().first);
  hard.push_back(sub->incoming().second);
  hard.push_back(sub->outgoing()[0]);
  hard.push_back(sub->outgoing()[1]);
  // boost to partonic CMS
  Lorentz5Momentum pcms = hard[0]->momentum()+hard[1]->momentum();
  LorentzRotation boost(-pcms.boostVector());
  for(PPtr part : hard) part->transform(boost);
  // set the wavefunctions
  vector<VectorWaveFunction> g1,g2,psi,g4;
  VectorWaveFunction( g1,hard[0],incoming,false, true,true,vector_phase);
  VectorWaveFunction( g2,hard[1],incoming,false, true,true,vector_phase);
  VectorWaveFunction(psi,hard[2],outgoing,true ,false,true,vector_phase);
  VectorWaveFunction( g4,hard[3],outgoing,true , true,true,vector_phase);
  // extract kinematic variables
  Energy M = hard[2]->mass();
  Energy2 M2 = sqr(hard[2]->mass());
  double phi = hard[2]->momentum().phi();
  Energy2 sh = (hard[0]->momentum()+hard[1]->momentum()).m2();
  Energy2 th = (hard[0]->momentum()-hard[2]->momentum()).m2();
  Energy2 uh = (hard[0]->momentum()-hard[3]->momentum()).m2();
  Energy2 um(uh-M2),tm(th-M2),sm(sh-M2);
  Complex phase = exp(Complex(0.,phi));
  Energy rstu = sqrt(th*uh/sh);
  // calculate the matrix element
  ProductionMatrixElement me(PDT::Spin1,PDT::Spin1,PDT::Spin1,PDT::Spin1);
  me(0,0,0,0)=(2.*sqr(phase)*sqr(sh))/(tm*um);
  me(0,0,0,2)=0;
  me(0,0,1,0)=0;
  me(0,0,1,2)=0;
  me(0,0,2,0)=0;
  me(0,0,2,2)=0;
  me(0,2,0,0)=2.*M2*sh*th*uh/(sqr(sm)*tm*um);
  me(0,2,0,2)=(2.*sqr(sh)*sqr(uh))/(sqr(phase)*sqr(sm)*tm*um);
  me(0,2,1,0)=(-2.*sqrt(2)*M*rstu*sqr(sh)*th)/(phase*sqr(sm)*tm*um);
  me(0,2,1,2)=(-2.*sqrt(2)*M*rstu*sqr(sh)*uh)/(pow(phase,3)*sqr(sm)*tm*um);
  me(0,2,2,0)=(2.*sqr(sh)*sqr(th))/(sqr(phase)*sqr(sm)*tm*um);
  me(0,2,2,2)=(2.*M2*sh*th*uh)/(pow(phase,4)*sqr(sm)*tm*um);
  me(2,0,0,0)=(2.*M2*pow(phase,4)*sh*th*uh)/(sqr(sm)*tm*um);
  me(2,0,0,2)=(2.*sqr(phase)*sqr(sh)*sqr(th))/(sqr(sm)*tm*um);
  me(2,0,1,0)=(2.*sqrt(2)*M*pow(phase,3)*rstu*sqr(sh)*uh)/(sqr(sm)*tm*um);
  me(2,0,1,2)=(2.*sqrt(2)*M*phase*rstu*sqr(sh)*th)/(sqr(sm)*tm*um);
  me(2,0,2,0)=(2.*sqr(phase)*sqr(sh)*sqr(uh))/(sqr(sm)*tm*um);
  me(2,0,2,2)=(2.*M2*sh*th*uh)/(sqr(sm)*tm*um);
  me(2,2,0,0)=0;
  me(2,2,0,2)=0;
  me(2,2,1,0)=0;
  me(2,2,1,2)=0;
  me(2,2,2,0)=0;
  me(2,2,2,2)=(2.*sqr(sh))/(sqr(phase)*tm*um);
  // test the spin averaged result
  // double test = 8.*sqr(sh)*(sqr(sh*sm)+sqr(th*tm)+sqr(uh*um))/sqr(sm*tm*um);
  // double aver = me.average();
  // cerr << "testing spin correlations " << test << " " << me.average() << " "
  //      << abs(test-aver)/(test+aver) << "\n";
  // construct the vertex
  HardVertexPtr hardvertex = new_ptr(HardVertex());
  // // set the matrix element for the vertex
  hardvertex->ME(me);
  // set the pointers and to and from the vertex
  for(unsigned int i = 0; i < hard.size(); ++i)
    hard[i]->spinInfo()->productionVertex(hardvertex);
  // boost back to lab
  boost = LorentzRotation(pcms.boostVector());
  for(PPtr part : hard)
    part->transform(boost);
}
