// -*- C++ -*-
//
// This is the implementation of the non-inlined, non-templated member
// functions of the TwoToThree class.
//

#include "TwoToThree.h"
#include "ThePEG/Interface/ClassDocumentation.h"
#include "ThePEG/Interface/Switch.h"
#include "ThePEG/EventRecord/Particle.h"
#include "ThePEG/Repository/UseRandom.h"
#include "ThePEG/Repository/EventGenerator.h"
#include "ThePEG/Utilities/DescribeClass.h"
#include "ThePEG/Persistency/PersistentOStream.h"
#include "ThePEG/Persistency/PersistentIStream.h"
#include "ThePEG/PDT/EnumParticles.h"
#include "ThePEG/MatrixElement/Tree2toNDiagram.h"
#include "ThePEG/Utilities/SimplePhaseSpace.h"
#include "ThePEG/Cuts/Cuts.h"
#include "Herwig/MatrixElement/TwoToThreePhaseSpace.h"
#include "Herwig/Utilities/Kinematics.h"

using namespace Herwig;

bool TwoToThree::generateKinematics(const double * r) {
  jacobian(1.);
  // first generate the mass of the onium/diquark state
  Energy ecm = sqrt(sHat());
  Energy mBc(ZERO);
  vector<Energy> mOut = {mePartonData()[3]->hardProcessMass(),mePartonData()[4]->hardProcessMass(),ZERO};
  if(mOpt_==0 || !massGen_) {
    mBc=mePartonData()[2]->mass();
  }
  else {
    Energy mmin = mePartonData()[2]->massMin(), mmax = min(mePartonData()[2]->massMax(),ecm-mOut[0]+mOut[1]);
    double jtemp(0.);
    mBc = massGen_->mass(jtemp,*mePartonData()[2],mmin,mmax,r[4]);
    jacobian(jacobian()*jtemp);
  }
  mOut[2]=mBc;
  if(ecm<mOut[0]+mOut[1]+mOut[2]) return false;
  // generate the momenta
  double jac = TwoToThreePhaseSpace::twoToThreeFS(ecm,mOut,r,meMomenta()[3],
  						  meMomenta()[4],meMomenta()[2],1.);
  if(jac<0.) return false;
  jacobian(jacobian()*jac);
  // check passes all the cuts
  vector<LorentzMomentum> out(3);
  tcPDVector tout(3);
  for(unsigned int ix=0;ix<3;++ix) {
    out[ ix] = meMomenta()[ix+2];
    tout[ix] = mePartonData()[ix+2];
  }
  if ( !lastCuts().passCuts(tout, out, mePartonData()[0], mePartonData()[1]) )
    return false;
  else
    return true;
}

CrossSection TwoToThree::dSigHatDR() const {
  return me2()*jacobian()*sqr(hbarc)/sHat();
}

void TwoToThree::persistentOutput(PersistentOStream & os) const {
  os << mOpt_ << massGen_;
}

void TwoToThree::persistentInput(PersistentIStream & is, int) {
  is >> mOpt_ >> massGen_;
}


// The following static variable is needed for the type
// description system in ThePEG.
DescribeAbstractClass<TwoToThree,HwMEBase>
describeHerwigTwoToThree("Herwig::TwoToThree",
			 "HwOniumParameters.so HwMEHadronOnium.so");

void TwoToThree::Init() {

  static ClassDocumentation<TwoToThree> documentation
    ("The TwoToThree class implemnts simple 2->3 phase space");
  
  static Switch<TwoToThree,unsigned int> interfaceMassOption
    ("MassOption",
     "Mass of the treatment of mas of the B_c state",
     &TwoToThree::mOpt_, 1, false, false);
  static SwitchOption interfaceMassOptionOnShell
    (interfaceMassOption,
     "OnShell",
     "Use the on-shell mass",
     0);
  static SwitchOption interfaceMassOptionOffShell
    (interfaceMassOption,
     "OffShell",
     "Use an off-shell mass generated by the MassGenerator object for the B_c state.",
     1);

}

