#! /usr/bin/env python
import logging
import sys
import os, yoda

"""%prog

Script for merging yoda files

"""

import sys
if sys.version_info[:3] < (2,4,0):
    print "rivet scripts require Python version >= 2.4.0... exiting"
    sys.exit(1)

if __name__ == "__main__":
    import logging
    from optparse import OptionParser, OptionGroup
    parser = OptionParser(usage="%prog aidafile aidafile2 [...]")
    parser.add_option("-o", "--out", dest="OUTFILE", default="-")
    verbgroup = OptionGroup(parser, "Verbosity control")
    verbgroup.add_option("-v", "--verbose", action="store_const", const=logging.DEBUG, dest="LOGLEVEL",
                         default=logging.INFO, help="print debug (very verbose) messages")
    verbgroup.add_option("-q", "--quiet", action="store_const", const=logging.WARNING, dest="LOGLEVEL",
                         default=logging.INFO, help="be very quiet")
    parser.add_option_group(verbgroup)
    (opts, args) = parser.parse_args()
    logging.basicConfig(level=opts.LOGLEVEL, format="%(message)s")

    ## Check args
    if len(args) < 1:
        logging.error("Must specify at least one AIDA histogram file")
        sys.exit(1)

    ## Get histos
    outhistos={}
    for file in args:
        if not os.access(file, os.R_OK):
            logging.error("%s can not be read" % file)
            break
        try:
            aos = yoda.read(file)
        except:
            logging.error("%s can not be parsed as yoda" % file)
            break
        ## Get histos from this YODA file
        for aopath, ao in aos.iteritems() :
            if(aopath.find("D0_2010_S8821313")>0) :
                if(aopath.find("d01")>0 and file.find("-e")>0) : 
                    outhistos[aopath] = ao
                elif(aopath.find("d02")>0 and file.find("-mu")>0) : 
                    outhistos[aopath] = ao
            elif(aopath.find("D0_2015_I1324946")>0) :
                if(file.find("LowMass")>0) : 
                    if(aopath.find("d02")>0) :
                        outhistos[aopath] = ao
                elif(file.find("HighMass")>0) : 
                    if(aopath.find("d03")>0 or aopath.find("d04")>0) :
                        outhistos[aopath] = ao
                else:
                    if(aopath.find("d01")>0) :
                        outhistos[aopath] = ao
            else :
                outhistos[aopath] = ao

    # output the yoda file
    yoda.writeYODA(outhistos,opts.OUTFILE)
    sys.exit(0)
