SOURCES := $(wildcard *.cc)

OBJECTS := $(SOURCES:.cc=.o) GlobalParameters.so

include ../Config/Makefile.common
# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


GlobalParameters.o: GlobalParameters.cc GlobalParameters.h\
	 ../../Pythia7/Interface/Interfaced.h \
	 ../../Pythia7/Config/Pythia7.h \
	 ../../Pythia7/Config/config.h \
	 ../../Pythia7/Pointer/Ptr.h \
	 ../../Pythia7/Pointer/RCPtr.fh \
	 ../../Pythia7/Pointer/PtrTraits.h \
	 ../../Pythia7/Pointer/RCPtr.h \
	 ../../Pythia7/Pointer/ReferenceCounted.h \
	 ../../Pythia7/Pointer/ReferenceCounted.icc \
	 ../../Pythia7/Pointer/RCPtr.icc \
	 ../../Pythia7/Utilities/Rebinder.fh \
	 ../../Pythia7/Utilities/Interval.fh \
	 ../../Pythia7/Utilities/ClassDescription.fh \
	 ../../Pythia7/Interface/InterfaceBase.fh \
	 ../../Pythia7/Persistency/PersistentOStream.fh \
	 ../../Pythia7/Persistency/PersistentIStream.fh \
	 ../../Pythia7/Config/Units.h \
	 ../../Pythia7/CLHEPWrap/Lorentz5Vector.fh \
	 ../../Pythia7/CLHEPWrap/LorentzVector.fh \
	 ../../Pythia7/CLHEPWrap/ThreeVector.fh \
	 ../../Pythia7/CLHEPWrap/Transverse.fh \
	 ../../Pythia7/CLHEPWrap/SystemOfUnits.h \
	 ../../Pythia7/CLHEPWrap/CLHEP.h \
	 ../../Pythia7/Config/Constants.h \
	 ../../Pythia7/Config/std.h \
	 ../../Pythia7/Config/Pointers.h \
	 ../../Pythia7/Config/Containers.h \
	 ../../Pythia7/Utilities/FixedSizeAllocator.h \
	 ../../Pythia7/Utilities/Debug.h \
	 ../../Pythia7/Utilities/Debug.icc \
	 ../../Pythia7/Utilities/FixedSizeAllocator.icc \
	 ../../Pythia7/Interface/InterfacedBase.h \
	 ../../Pythia7/Misc/Named.h \
	 ../../Pythia7/Misc/Named.icc \
	 ../../Pythia7/Utilities/ClassDescription.h \
	 ../../Pythia7/Utilities/ClassTraits.h \
	 ../../Pythia7/Utilities/DescriptionList.h \
	 ../../Pythia7/Utilities/DescriptionList.icc \
	 ../../Pythia7/Utilities/ClassDescription.icc \
	 ../../Pythia7/Utilities/ClassDescription.tcc \
	 ../../Pythia7/Utilities/HoldFlag.h \
	 ../../Pythia7/Utilities/HoldFlag.icc \
	 ../../Pythia7/Interface/InterfacedBase.xh \
	 ../../Pythia7/Interface/InterfaceBase.h \
	 ../../Pythia7/Interface/InterfaceBase.xh \
	 ../../Pythia7/Misc/Exception.h \
	 ../../Pythia7/Misc/Exception.fh \
	 ../../Pythia7/Utilities/sstream.h \
	 ../../Pythia7/Misc/Exception.icc \
	 ../../Pythia7/Interface/InterfaceBase.icc \
	 ../../Pythia7/Interface/InterfacedBase.icc \
	 ../../Pythia7/Interface/Interfaced.icc \
	 ../../Herwig++/Config/Herwig.h \
	 ../../Pythia7/CLHEPWrap/PhysicalConstants.h \
	 ../../Pythia7/Interface/ClassDocumentation.h \
	 ../../Pythia7/Interface/ClassDocumentation.fh \
	 ../../Pythia7/Interface/ClassDocumentation.icc \
	 ../../Pythia7/Interface/Parameter.h \
	 ../../Pythia7/Interface/Parameter.xh \
	 ../../Pythia7/Interface/Parameter.fh \
	 ../../Pythia7/Interface/Parameter.icc \
	 ../../Pythia7/Interface/Parameter.tcc \
	 ../../Pythia7/Interface/Switch.h \
	 ../../Pythia7/Interface/Switch.fh \
	 ../../Pythia7/Interface/Switch.xh \
	 ../../Pythia7/Interface/Switch.icc \
	 ../../Pythia7/Interface/Switch.tcc \
	 ../../Pythia7/Persistency/PersistentOStream.h \
	 ../../Pythia7/Persistency/PersistentOStream.xh \
	 ../../Pythia7/Persistency/PersistentOStream.icc \
	 ../../Pythia7/Persistency/PersistentIStream.h \
	 ../../Pythia7/Persistency/InputDescription.h \
	 ../../Pythia7/Persistency/InputDescription.icc \
	 ../../Pythia7/Persistency/PersistentIStream.icc \
	 ../../Pythia7/Persistency/PersistentIStream.tcc

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
