// Template MadGraph process file
// Replace process-specific marked values with values 
// taken from CPPProcess.h file generated by MadGraph

#ifndef MG5_Sigma_mssm_process_H
#define MG5_Sigma_mssm_process_H

#include <complex> 
#include <vector> 
#include "Parameters_mssm.h"

using namespace std; 


class MG_process
{
  public:

    // Constructor.
    MG_process() {}

    // Initialize process using parameter card (slow)
    virtual void initProc(string param_card_name); 

    // Initialize process using Herwig parameters
    virtual void initProc(map<string, double> & MGParams); 

    // Calculate flavour-independent parts of cross section.
    virtual void sigmaKin(vector<std::complex<double> >& amps, const vector<int>& hel); 

    // Set momenta for matrix element evaluation
    void setMomenta(vector < double * > & momenta){p = momenta;}
 
    // number of external particles ** Replace
    static const int nexternal = 4; 

    // number of colour ordered amplitudes ** Replace
    static const int namplitudes = 1; 
    std::complex<double> amp[namplitudes]; 

  private:
    // Calculate wavefunctions
    void calculate_wavefunctions(const int hel[]); 

    // number of wavefunctions used in calculate_wavefunctions ** Replace
    static const int nwavefuncs = 5; 
    std::complex<double> w[nwavefuncs][18]; 

    // Pointer to the model parameters
    Parameters_mssm * pars; 

    // vector with external particle masses
    vector<double> mME; 

    // vector with momenta 
    vector < double * > p; 
 
}; 


#endif  // MG5_Sigma_mssm_process_H
