#!/bin/bash

cat << EOF > /dev/stderr

************************************************************
*                                                          *
*          Herwig++ has been renamed to Herwig             *
*                                                          *
*  You need to rename Herwig++ in your scripts, this       *
*  convenience wrapper will disappear in the next version! *
*                                                          *
************************************************************

EOF
sleep 3
exec @BINDIR@/Herwig "$@"
