#! /bin/bash

# this is very hard-coded to the exact format of CHISQ.log

grep '^Chi Square' $1 | grep -v ' nan ' | \
sed 's!^.* = \(.*\) for \(.*\) degrees .*$!\1 \2!' | \
awk ' { chisqsum+=$1; dofsum+=$2}
 END { chiperdof=chisqsum/dofsum; printf("YVALUE = %g\n", chiperdof) } '
